vers1 = "Ik ben Rafboerhout"
ver2 =  "Na mijn opleiding ga ik voor goud"
vers3 = "Ik werk nu als bezorger"
vers4 = "Mijn moeder werkt als dierenverzorger"
vers5 = "Ik zit nu op het MA"
vers6 = "Dat is waar ik elke dag naar toe ga"
vers7 = "Mijn opleiding is software developer"
vers8 = "Soms heb ik een vastloper"
vers9 = "We werken met python"
vers10 = "Ik wist niet dat ik dat kon"
vers11 = "Ik hoop dat het een heel leuk jaar word"
vers12 = "Ik zit hier nog 4 jaar"
vers13 = "Dus hoopelijk ben ik snel klaar"
vers14 = "dit is het einde van mijn gedicht"
vers15 = "Ik ben blij kijk maar naar mijn gezicht"

print(vers1,ver2,vers3,vers4,vers5,vers6,vers7,vers8,vers9,vers10,vers11,vers12,vers12,vers13,vers14,vers15)
